left: "phenotype.parquet"
right: "genotype.parquet"
output: "phenotype_genotype_merged.parquet"
join_type: "INNER"
join_keys: ["BioSample_ID", "assembly_ID", "antibiotic_ontology"]
conditions:
  - left_key: "resistance_phenotype"
    condition: "IN ('resistant', 'susceptible', 'susceptible-dose dependent', 'intermediate')"
left_cols: 
  - "BioSample_ID"
  - "INSDC_secondary_accession"
  - "antibiotic_ontology"
  - "assembly_ID"
  - "collection_year"
  - "ISO_country_code"
  - "host"
  - "host_age"
  - "host_sex"
  - "isolation_source"
  - "isolation_source_category"
  - "isolation_latitude"
  - "isolation_longitude"
  - "AMR_associated_publications"
  - "used_ECOFF"
  - "database"
  - "antibiotic_name"
  - "ast_standard"
  - "laboratory_typing_method"
  - "measurement"
  - "measurement_sign"
  - "measurement_units"
  - "platform"
  - "resistance_phenotype"
  - "antibiotic_ontology_link"
  - "country"
  - "geographical_region"
  - "geographical_subregion"
right_cols:
  - "genus"
  - "species"
  - "organism"
  - "isolate"
  - "taxon_id"
  - "region"
  - "region_start"
  - "region_end"
  - "strand"
  - "id"
  - "gene_symbol"
  - "amr_element_symbol"
  - "element_type"
  - "element_subtype"
  - "class"
  - "subclass"
  - "split_subclass"
  - "evidence_accession"
  - "evidence_type"
  - "evidence_link"
  - "evidence_description"
